### ISSUE TITLE
Docker image for robots

### ISSUE THREAD

**Issue by peaceiris** [google/robotstxt#69]
## Docker image

I have created an alpine linux-based Docker image that includes a binary of google/robotstxt. If you are consider to publish it officially, please let me know. I believe I can contribute to this project.

Dockerfile: https://github.com/peaceiris/docker-images/tree/main/images/robotstxt

### docker run

```console
$ wget https://github.com/robots.txt
$ docker run --rm -v ./robots.txt:/root/robots.txt peaceiris/robotstxt:v1.0.0 /root/robots.txt Googlebot "https://github.com/google"
user-agent 'Googlebot' with URI 'https://github.com/google': ALLOWED
```

### GitHub Actions

```yaml
name: robots.txt

on:
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
    container:
      image: ghcr.io/peaceiris/robotstxt:v1.0.0
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        run: |
          # Validate a local robots.txt
          robots ./assets/robots.txt Googlebot "https://github.com/"

          # Download and validate
          curl -s https://github.com/robots.txt --output robots.txt
          robots robots.txt Googlebot "https://github.com/google"
```
